### ISSUE TITLE
Exception due to invalid culture name in assembly

### ISSUE THREAD

**Issue by nhedlund** [StevenRasmussen/EFCore.SqlServer.NodaTime#9]
I get an exception when instantiating our DbContext class due to an invalid culture name "English (United States)".

Looking at the source code I found this specified in the csproj-file. If this should be a culture name I think you should change it to "en-US", but maybe you should consider just removing that row from the csproj instead?

Not sure if libraries should specify this attribute, it should probably be specified in the application itself - but I am not sure, I usually try to avoid localization at all cost.

More info about this attribute: https://docs.microsoft.com/en-us/dotnet/api/system.resources.neutralresourceslanguageattribute?view=netcore-3.1

**Exception:**

System.ArgumentException
The NeutralResourcesLanguageAttribute on the assembly "SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime, Version=1.3.2.0, Culture=neutral, PublicKeyToken=null" specifies an invalid culture name: "English (United States)".
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(Assembly a, UltimateResourceFallbackLocation& fallbackLocation)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(String baseName, Assembly assembly)
   at SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime.Properties.Resources.get_ResourceManager()
   at SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime.Properties.Resources.get_ServicesMissing()
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.NodaTimeOptionsExtension.Validate(IDbContextOptions options)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ValidateOptions(IDbContextOptions options)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)

**Comment by StevenRasmussen** [comment]
@nhedlund - Thanks for reporting this!  Not sure why I had that in there. I just published v1.3.3 to NuGet... should be available shortly.
